### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by MemeHoovy** [Leather128/FabricEngine#4]
Hello, whenever I attempt to compile the game, these errors show up.

```
src/funkin/scenes/TitleScreen.hx:6: characters 8-47 : Type not found : flixel.addons.transition.TransitionData
src/funkin/scenes/TitleScreen.hx:7: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
src/funkin/scenes/FunkinScene.hx:7: characters 27-54 : Type not found : flixel.addons.ui.FlxUIState
src/funkin/scenes/FunkinScene.hx:7: characters 27-54 : ... For function argument 'child'
src/Main.hx:7: lines 7-80 : ... Defined in this class
src/funkin/scenes/FunkinScene.hx:7: characters 27-54 : Type not found : flixel.addons.ui.FlxUIState
src/Main.hx:7: lines 7-80 : ... Defined in this class
```
I'm using flixel 4.11.0, and this error could be because of flixel 5.0.0, basically I'm pretty sure this is a flixel 5.0.0 thing, albeit I don't wanna use 5.0.0 since it's not finished and it breaks compiling with projects that don't _use_ 5.0.0

oh and btw, I'm using haxe 4.2.5

**Comment by Leather128** [comment]
no the issue is that to build this project you need to use the fork of
flixel from me (or yoshi i think? not sure if that one still works since
i’m not using it but ae)

**Comment by MemeHoovy** [comment]
oh OK I didn't know that, maybe you could've put that in the readme so people know _what version of flixel to use_

**Comment by Leather128** [comment]
that is fair but also you gotta remember that this project is not at all finished and the readme is just kind of a joke atm (until i make a real one later down the line)
