### ISSUE TITLE
Switching scenes crash

### ISSUE THREAD

**Issue by Squidtito** [Leather128/FabricEngine#6]
When you go in and out of a scene (menus) at the same time the game crashes.

**Comment by Leather128** [comment]
can you provide a bit more detail on what you mean as i am confused

**Comment by Squidtito** [comment]
So, I'm in main menu right? Well I go into freeplay and press esc going to the title menu, which is probably making the engine trying to go to 2 things at once, making it confused so..

**Comment by Leather128** [comment]
do you by chance press esc more than once? because if esc is pressed on the title screen the game will close by itself

**Comment by Squidtito** [comment]
XD Yea I am, sorry.

**Comment by Leather128** [comment]
it's fine :+1:
