### ISSUE TITLE
Score feedback not visible

### ISSUE THREAD

**Issue by Squidtito** [Leather128/FabricEngine#7]
I just found out that wasn't getting score feedback or otherwise seeing it at least, it might be because of the score feedback not being relative to where the camera is? Since in normal stages like stage spooky (Which in spooky the score feedback is a bit higher up in the screen) I can see them, but in my stage which is a lot more higher up so.. Sorry if this doesn't make sense lol.

**Comment by Leather128** [comment]
are you saying the score counter isn't showing up?

**Comment by Squidtito** [comment]
It is showing, just not at the relative position of the camera

**Comment by Leather128** [comment]
the score has never been relative to the camera, it's on the ui camera which is seperate so you can always see it, if you want you could set `ui.cameras = [FlxG.camera];` to make it on the main camera, although i'm not sure why you would want to

**Comment by Squidtito** [comment]
Ah alright, I don't think there is really anymore bugs at the moment. Thanks for responding ^^

**Comment by Leather128** [comment]
:+1:
